pipeline {
  agent any
  stages {
    stage('Build and Test') {
      failFast true
      parallel {
        stage('Coffeelake clang-7 SGX1-FLC Debug') {
          agent {
            docker {
              image 'oetools-azure:1.6'
              label 'hardware'
              args '-v /dev/sgx:/dev/sgx'
            }
          }

          steps {
            timeout(15) {
              sh './scripts/test-build-config -p SGX1FLC -b Debug -d --compiler=clang-7'
            }
          }
        }
      }
    }
  }
}
